services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Models/txt.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
